### ISSUE TITLE
python setup.py develop fails

### ISSUE THREAD

**Issue by tom-seddon** [HydraChain/hydrachain#14]
Following the setup instructions, I run `python setup.py develop`. This fails with an error, because it can't write to a file under `/usr/local/`.

Should this command in fact be run with sudo? Or is it actually supposed to write to the home folder (and there's probably something wrong with my setup)?

Thanks,

--Tom

**Comment by czepluch** [comment]
Have you tried running it with sudo? Did it work?

Also what version of Python are you using?

**Comment by tom-seddon** [comment]
I'm using python 2.7.6.

I did try it with sudo, and it got further, but I got some strange errors that make me wonder whether I should be using python 3 instead. I had a couple like these during the install:

    warning: no previously-included files matching '*.py[co]' found under directory '*'
      File "build/bdist.linux-x86_64/egg/rlp/utils_py3.py", line 6
        class Atomic(metaclass = abc.ABCMeta):

And at the end, this:

```gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
  CC       src/tests-tests.o
  CCLD     tests
error: [Errno 9] Bad file descriptor
error: [Errno 2] No such file or directory <built-in function listdir> /tmp/easy_install-Zzkfrw/c_secp256k1-0.0.4/egg-dist-tmp-ZPVjHI
error: [Errno 2] No such file or directory <built-in function listdir> /tmp/easy_install-Zzkfrw/c_secp256k1-0.0.4/egg-dist-tmp-ZPVjHI
error: [Errno 2] No such file or directory <built-in function listdir> /tmp/easy_install-Zzkfrw/c_secp256k1-0.0.4/egg-dist-tmp-ZPVjHI
error: [Errno 2] No such file or directory <built-in function listdir> /tmp/easy_install-Zzkfrw/c_secp256k1-0.0.4/egg-dist-tmp-ZPVjHI
error: [Errno 2] No such file or directory <built-in function listdir> /tmp/easy_install-Zzkfrw/c_secp256k1-0.0.4/egg-dist-tmp-ZPVjHI```

In the end, hydrachain didn't run:

```Traceback (most recent call last):
  File "/usr/local/bin/hydrachain", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'c-secp256k1' distribution was not found and is required by hydrachain```

Any guidance would be appreciated.

I'm doing this in a vagrant ubuntu VM that starts out with basically nothing, so it's possible I'm just missing some dependency. I've already been through this with a number of things (python-pip, autoconf, python-dev, libtool, libffi-dev, libssl-dev).

Thanks,

--Tom

**Comment by czepluch** [comment]
Okay. Thanks for the error messages. You should not be using python3 at the moment and I don't think you're doing anything wrong. It seems we broke the c-secp256k1 lib. I will look into fixing it tomorrow. It's a bit late in Europe right now, so I hope you can hang tight until then.

**Comment by tom-seddon** [comment]
Great, thanks. No problem about waiting - my own time zone is BST! I've just been working funny hours today :)

--Tom

**Comment by heikoheiko** [comment]
I removed the dependency for now.

**Comment by heikoheiko** [comment]
Regarding `sudo`, the recommended way to install it is using `virtualenv`. 
For your plans, consider to take a look at the Dockerfile: https://github.com/HydraChain/hydrachain/tree/master/docker

**Comment by raymondcarl** [comment]
Hi,

I am quite a beginner programmer, but I had all of the exact same issues with the error messages and not being to run.  I also tried with both python 2.7 and 3.4.  I just cloned the git today.  Did you already remove the dependency on c-secp256k1 lib?

```
    pkg_resources.DistributionNotFound: The 'c-secp256k1' distribution was not found and is required by hydrachain
```

**Comment by raymondcarl** [comment]
Never mind.  Works fine when using the docker template.
