### ISSUE TITLE
Can't resolve name of alice in contract creation example

### ISSUE THREAD

**Issue by retotrinkler** [HydraChain/hydrachain#25]
In the example here: https://github.com/ethereum/pyethapp/wiki/The_Console

I can deploy the contract, see the address with tx.creates, register a name: 
`tx = namereg.register('alice')` with:

```
In [38]: eth.find_transaction(tx)
Out[38]: {'block': <Block(#18 513a2899)>, 'index': 0, 'tx': <Transaction(c33f)>}
```

But get an empty response when I try to resolve the name ie:

```
In [39]: namereg.resolve(eth.coinbase)
Out[39]: ''
```

**Comment by heikoheiko** [comment]
please provide the relevant logs (debug level).

**Comment by retotrinkler** [comment]
```
DEBUG:eth.pb.tx TX NEW tx_dict={'nonce': 1048588, 'hash': '181a18e77ba7ce3dbc29dc620002dc2201ced2cfac62ec60c6453558f0eb2982', 'sender': '8ed66d0dd4b88fb097a3a3c8c10175b8cadb1c66', 'startgas': 25000, 'value': 0, 'to': '1d063c0e74313e74c9d96c9eeff0a5055e185884', 's': 0, 'r': 0, 'v': 0, 'data': 'U\xealG\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8e\xd6m\r\xd4\xb8\x8f\xb0\x97\xa3\xa3\xc8\xc1\x01u\xb8\xca\xdb\x1cf', 'gasprice': 60000000000}
DEBUG:eth.pb.tx _res_ data=[] result=1 gas_remained=2320
DEBUG:eth.pb.tx TX APPLIED data=[] result=1 gas_remained=2320
DEBUG:eth.pb.tx TX SUCCESS data=[]
```

**Comment by heikoheiko** [comment]
looks like a different tx.hash

**Comment by retotrinkler** [comment]
i agree.
`'U\xealG\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8e\xd6m\r\xd4\xb8\x8f\xb0\x97\xa3\xa3\xc8\xc1\x01u\xb8\xca\xdb\x1cf'.encode('hex')`
resolves to:
`'55ea6c470000000000000000000000008ed66d0dd4b88fb097a3a3c8c10175b8cadb1c66'`
not sure if thats relevant though

**Comment by heikoheiko** [comment]
does it work when using jsonrpc?

**Comment by retotrinkler** [comment]
will look into it.
