### ISSUE TITLE
Support min_block_time / Proposer should be able to collect multiple txs. 

### ISSUE THREAD

**Issue by heikoheiko** [HydraChain/hydrachain#46]
Problem: Currently most blocks have only 1tx / So we have the full consensus protocol overhead for every tx.

Solution: Proposers should collect multiple txs before proposing a block. Behavior needs to be changed, to wait a `min_block_time` before proposing a block. So this acts as a timeout for the proposer only. This timeout must be shorter than the global round timeout. Also this timeout should only be used in Round0.

**Comment by konradkonrad** [comment]
fixed (see c63b4e4)
